#source("/Users/yilinsmac/Desktop/sigfile functions/real/myMCMC14a_vtest_evk_realtest function.r")
## function to perform MCMC based on previous functions: 
myMCMC14a_vtest_evk_realtestyes=function(data,v,k=10,erv1=1,erv2=rep(0.01,14),tby=1,n=3000){ 
	# data is the pseudodata_real() output to deal with; erv1 is the noise variance, erv2 is the variance of proposal distribution; n is the number of times of MCMC.

# this loops over each parameter in one iteration.

# erv2 is a vector of normal proposal variance of dim 1*14
# v is the index(es) for the testing parameter(s),would just loop over the parameters specified by v, and the others would have initial guess set to true parameter values.

# k is such that we only record every kth iteration.

##  now start implementing MCMC:
 # "real"data is generated by previous function
#erv2[14]=0
a={}#a0=c(0.2,0.2,0.3,0.4,0.4,0.9,0.8,0.7,0.6,0.6,0.4,0.3,0.2,0.01)
a0=rep(0.5,14)
a0[v]=0.5
a0[14]=0.01
#a0=runif(13) #so rho is also guessed from a uniform?
a=rbind(a,a0)
 
# log-likelihood l for datat using guess:
lold=myloglk14realtest(a1=a0,tby=tby,data=data,erv1=erv1)
 

count=rep(0,14)
curpars=a0 #current 14-d parameter guess at iteration 0
# for loop to loop over n iterations
for (MCitr in 1:(n-1)){


# for loop to loop over 14 parameters
 for (m in v){
mu=curpars[m]	#get out current guess for the mth parameter we are interested in

a2=rnorm(1,mu,erv2[m]) 
if (a2<0 || a2>1){
	curpars[m]=mu
 # a[(MCitr+1),]=a[MCitr,]
# print(paste("acurrent", a[MCtime],", aproposed rejected=", a2,"outside of the prior"))
} else {

	# to compute log-likelihood based on guess a2:
curpars[m]=a2	
lnew=myloglk14realtest(a1=curpars,tby=tby,data=data,erv1=erv1)


 
## to compute M-H
if (m==14){
	  alpha=min(1,exp(lnew-lold)*mu3/c2)
} else {
  alpha=min(1,exp(lnew-lold))
  }
   u=runif(1)
#   print(paste("MCtime=", MCtime,", lold=",lold, ", lnew=",lnew, "likratio=",exp(lnew-lold) ))
   if (u<=alpha){
   	curpars[m]=a2
	#a[(MCitr+1),]=curpars
	count[m]=count[m]+1
	lold=lnew #the proposal has become the current (old) stage 
#	print(paste("acurrent", a[MCtime],", aproposed accepted=", a2,", alpha=", alpha,", u=",u ))
      } # end if
       else{
		curpars[m]=mu
		#a[(MCitr+1),]=a[MCitr,]
#print(paste("acurrent", a[MCtime],", aproposed rejected=", a2,", alpha=", alpha,", u=",u ))
	 }# end else
	 } #end else
	lnew=NA	 
 }#end for m in v

lnew=NA	

if (MCitr %% k ==0){
a=rbind(a,curpars)
}

} #end for (MCtime 1:n-1)
print(paste('acceptance rate=',count/n,'lold=',lold,'a0=',a0))
return(a)
}