
datat=pseudodata(t=30,tby=1,c8=0.5)

## plot of likelihood
# m is the index of the parameter of interest
# psdata is the real data to compute the likelihood of the indexed parameter
likelihoodplot=function(m,psdata,t=30,tby=1){

likvec=lapply(seq(0.01,0.99,by=0.001),function(i) myLikelihood(m,a1=i,t=t,tby=tby,psdata,erv1=0.1))

llp=plot(seq(0.01,0.99,by=0.001),as.numeric(likvec), xlab="a1", ylab="likelihood",main=paste("m=",m))
return(llp)
}


# trace plot
traceplot=function(a){ # a is the output of MCMC, the sequence of candidate for parameter value generated by MCMC
	plot(a,type='l',xlab="MCMC iteration", ylab="a1", main="trace plot")
}

pvalcpa=function(psdata,t=30,tby=0.1,m){# psdata is the real data, t and tby are used to generate number of data points using t/tby, m specifies which parameter to focus on.

if (m==1){
	plot(psdata,col='red',main='i1')
	for (p in seq(0.1,0.9,by=0.1)){
	lines(deterministic(i1=p, t=t, tby=tby))
}}
if (m==2){
	plot(psdata,col='red',main='i2')
	for (p in seq(0.1,0.9,by=0.1)){
	lines(deterministic(i2=p, t=t, tby=tby))
}}
if (m==3){
	plot(psdata,col='red',main='i3')
	for (p in seq(0.1,0.9,by=0.1)){
	lines(deterministic(i3=p, t=t, tby=tby))
}}
if (m==4){
	plot(psdata,col='red',main='i4')
	for (p in seq(0.1,0.9,by=0.1)){
	lines(deterministic(i4=p, t=t, tby=tby))
}}
if (m==5){
	plot(psdata,col='red',main='i5')
	for (p in seq(0.1,0.9,by=0.1)){
	lines(deterministic(i5=p, t=t, tby=tby))
}}
if (m==6){
	plot(psdata,col='red',main='c1')
	for (p in seq(0.1,0.9,by=0.1)){
	lines(deterministic(c1=p, t=t, tby=tby))
}}
if (m==7){
	plot(psdata,col='red',main='c2')
	for (p in seq(0.1,0.9,by=0.1)){
	lines(deterministic(c2=p, t=t, tby=tby))
}}
if (m==8){
	plot(psdata,col='red',main='c3')
	for (p in seq(0.1,0.9,by=0.1)){
	lines(deterministic(c3=p, t=t, tby=tby))
}}
if (m==9){
	plot(psdata,col='red',main='c4')
	for (p in seq(0.1,0.9,by=0.1)){
	lines(deterministic(c4=p, t=t, tby=tby))
}}
if (m==10){
	plot(psdata,col='red',main='c5')
	for (p in seq(0.1,0.9,by=0.1)){
	lines(deterministic(c5=p, t=t, tby=tby))
}}
if (m==11){
	plot(psdata,col='red',main='c6')
	for (p in seq(0.1,0.9,by=0.1)){
	lines(deterministic(c6=p, t=t, tby=tby))
}}
if (m==12){
	plot(psdata,col='red',main='c7')
	for (p in seq(0.1,0.9,by=0.1)){
	lines(deterministic(c7=p, t=t, tby=tby))
}}
if (m==13){
	plot(psdata,col='red',main='c8')
	for (p in seq(0.1,0.9,by=0.1)){
	lines(deterministic(c8=p, t=t, tby=tby))
}}
}

allplots=function(a,m,t,tby){ # t, tby is used in pseudodata etc. to generate number of data points by t/tby, m is the index of the parameter to infer, a is the real data to look at.
	pdf("all plots.pdf")
	par(mfrow=c(2,2))
	likelihoodplot(m=m,psdata=a,t=t,tby=tby)
	b=myMCMC(a,t=t,tby=tby,m=m)
	traceplot(b)
	hist(b,main='histogram',xlab='par',ylab='frequency')
	pvalcpa(a,t=t,tby=tby,m=m)	
	dev.off()
	return(m)
}

