## cleaning up for wk6 meeting

## function to generate data: input coef, return the ratio data
pseudodata=function(i1=0.2,i2=0.2,i3=0.2,i4=0.2,i5=0.2,c1=0.04,c2=0.8,c3=0.19,c4=0.9,c5=0.2,c6=0.88,c7=0.4,c8=0.9,t=30,tby=0.1){
##  Simulate pesudo-data first: 
# kit to solve Sys of ODE's
pol<-function(t,y,mu){
	list(c(
	mu[1]*y[1]*(1-(y[1]+y[2]+y[3]+y[4]+y[5]))-mu[2]*y[1],
	mu[2]*y[1]+mu[3]*y[2]*(1-(y[1]+y[2]+y[3]+y[4]+y[5]))-mu[4]*y[2],
	mu[4]*y[2]-mu[5]*y[3],
	mu[6]*y[4]*(1-(y[1]+y[2]+y[3]+y[4]+y[5]))-mu[7]*y[4],
	mu[7]*y[4]-mu[8]*y[5]
	))
}

yini<-c(w1=i1,w2=i2,w3=i3,w4=i4,w5=i5)

# simulated "data": datat
dt<-ode(y=yini,func=pol,times=seq(0,t,by=tby),parms=c(c1,c2,c3,c4,c5,c6,c7,c8)) 
datat=dt[,6]/(dt[,6]+2*dt[,4])
return (datat)
}

## function to perform MCMC based on previous function: 
myMCMC=function(psdata,erv1=0.1,erv2=0.1,t=30,tby=0.1,n=1000){ #psdata is the real data to deal with; erv1 is the noise variance, erv2 is the variance of proposal distribution; n is the number of times of MCMC.

##  now start implementing MCMC:
 # "real"data is generated by previous function
a=rep(NA,n)
a1=runif(1) 
a[1]=a1
gt1=pseudodata(c8=a1,t=t,tby=tby)
 
# log-likelihood l for datat using guess:
l=rep(1,2)
 for (tmpts in 1:(t/tby)) {
   lp=dnorm(gt1[tmpts], datat[tmpts], erv1,log=TRUE) 
   l[1]=l[1]+lp
  }
 
# Using for-loop
for (MCtime in 1:(n-1)){
# now propose a new candidate for a:
a2=rnorm(1,a[MCtime],erv2) 
if (a2<0 || a2>1){
 a[MCtime+1]=a[MCtime]
} else {
 gt2<-pseudodata(c8=a2,t=t,tby=tby)

# to compute log-likelihood based on guess a2:
 for (tmpts in 1:(t/tby)) {
   lp=dnorm(datat[tmpts],gt2[tmpts],0.1,log=TRUE) #assuming variance to be 1 for now
   l[2]=l[2]+lp
  }
 
## to compute M-H
  alpha=min(1,exp(l[2]-l[1]))
   u=runif(1)
   if (u<=alpha){
	a[MCtime+1]=a2
	l[1]=l[2]
      } else{
		a[MCtime+1]=a[MCtime]

	 }
	 }
}
d=hist(a[(n-500):n])
return(d)
}


