qtfitplot=function(psdata,m,sz=100,n=3000,l=1000,t=50, tby=1,sf=0.01,erv1=1,erv2=0.1){ 
	# a is the real data,
	#sz is the number of samples to draw from posterior c, 
	#where c would be generated by myMCMC(),its size would be n.
 plot(psdata,ylim=c(0,1),main='fit to data using quantiles',ylab='data',xlab="months")
	c=myMCMC(psdata=psdata,m=m,n=n, t=t,tby=tby,sf=sf,erv1=erv1,erv2=erv2)
	w=lattice(m=m,c=c,t=t,tby=tby,l=l,sz=sz)
	s=qtles(w,t=t,tby=tby)
	lines(s[,1],col='red') # 25% quantile
	lines(s[,2],col='blue') # 50% quantile
	lines(s[,3],col='green') # 75% quantile
	legend(x=35,y=0.98,legend=c('25% quantile','50% quantile',"75% quantile"),col=c('red','blue','green'),lty=c('solid','solid','solid'),box.lty='dashed')

	return(m)

}
