source("/Users/yilinsmac/Desktop/sigfile functions/13d/myMCMC14 function.r")
## function to perform MCMC based on previous functions: 
myMCMC14=function(psdata,erv1=1,erv2=0.1,t=50,tby=1,n=3000){ #psdata is the real data to deal with; erv1 is the noise variance, erv2 is the variance of proposal distribution; n is the number of times of MCMC.

#i don't know what this is

##  now start implementing MCMC:
 # "real"data is generated by previous function
a=matrix(nrow=n,ncol=14)
a0=runif(14) #so rho is also guessed from a uniform?
a[1,]=a0
 
# log-likelihood l for datat using guess:
lold=myloglk14(a1=a0,t=t,tby=tby,psdata=psdata,erv1=erv1)
 

count=rep(0,14)
# for loop to loop over n iterations
for (MCitr in 1:(n-1)){
curpars=a[MCitr,] #current 14-d parameter guess at iteration MCitr

# for loop to loop over 14 parameters
 for (m in seq(1,14,by=1)){
mu=curpars[m]	#get out current guess for the mth parameter we are interested in

a2=rnorm(1,mu,erv2) 
if (a2<0 || a2>1){
	curpars[m]=mu
 # a[(MCitr+1),]=a[MCitr,]
# print(paste("acurrent", a[MCtime],", aproposed rejected=", a2,"outside of the prior"))
} else {

	# to compute log-likelihood based on guess a2:
curpars[m]=a2	
lnew=myloglk14(a1=curpars,t=t,tby=tby,psdata=psdata,erv1=erv1)

 
## to compute M-H
  alpha=min(1,exp(lnew-lold))
   u=runif(1)
#   print(paste("MCtime=", MCtime,", lold=",lold, ", lnew=",lnew, "likratio=",exp(lnew-lold) ))
   if (u<=alpha){
   	curpars[m]=a2
	#a[(MCitr+1),]=curpars
	count[m]=count[m]+1
	lold=lnew #the proposal has become the current (old) stage 
#	print(paste("acurrent", a[MCtime],", aproposed accepted=", a2,", alpha=", alpha,", u=",u ))
      } # end if
       else{
		curpars[m]=mu
		#a[(MCitr+1),]=a[MCitr,]
#print(paste("acurrent", a[MCtime],", aproposed rejected=", a2,", alpha=", alpha,", u=",u ))
	 }# end else
	 } #end else
	
lnew=NA	 
a[(MCitr+1),]=curpars
} #end for m=1,...,14
} #end for (MCtime 1:n-1)
return(a)
}