#source("/Users/yilinsmac/Desktop/sigfile functions/14d/myMCMC14b function.r")
## function to perform MCMC based on previous functions: 
myMCMC14b=function(psdata,erv1=1,erv21=0.01,erv22=0.01,erv23=0.01,t=50,tby=1,n=3000){ 
#psdata is the real data to deal with; 
# erv1 is the noise variance, 
# erv21-23 is the variance of proposal distribution for i1-i5,c1-c8,rho respectively; 
#n is the number of iterations in MCMC.

#this loops only one block of parameters in one iteration


##  now start implementing MCMC:
 # "real"data is generated by previous function
library(MASS)
a=matrix(nrow=n,ncol=14)
a0=runif(14) #so rho is also guessed from a uniform?
a[1,]=a0
 
# log-likelihood l for datat using guess:
lold=myloglk14(a1=a0,t=t,tby=tby,psdata=psdata,erv1=erv1)

count=rep(0,3)
##i1-i5:
    # Using for-loop
for (MCitr in 1:(n-1)){
curpars=a[MCitr,]
 	## i1,...,i5
mu1=curpars[1:5]	#get out current guesses for the  parameter block we are interested in

a2=mvrnorm(1,mu1,Sigma=erv21*diag(5))
#a2=rnorm(5,mu1,erv21) 
if (a2[1]<0 || a2[2]<0 || a2[3]<0 || a2[4]<0 || a2[5]<0 || a2[1]>1|| a2[2]>1|| a2[3]>1|| a2[4]>1|| a2[5]>1){
	curpars[1:5]=mu1
  a[(MCitr+1),]=a[MCitr,]
# print(paste("acurrent", a[MCtime],", aproposed rejected=", a2,"outside of the prior"))
} else {

	# to compute log-likelihood based on guess a2:
curpars[1:5]=a2	
lnew=myloglk14(a1=curpars,t=t,tby=tby,psdata=psdata,erv1=erv1)

 
## to compute M-H
  alpha=min(1,exp(lnew-lold))
   u=runif(1)
#   print(paste("MCtime=", MCtime,", lold=",lold, ", lnew=",lnew, "likratio=",exp(lnew-lold) ))
   if (u<=alpha){
   	curpars[1:5]=a2
	a[(MCitr+1),]=curpars
	count[1]=count[1]+1
	lold=lnew #the proposal has become the current (old) stage 
#	print(paste("acurrent", a[MCtime],", aproposed accepted=", a2,", alpha=", alpha,", u=",u ))
      } # end if
       else{
		curpars[1:5]=mu1
		a[(MCitr+1),]=a[MCitr,]
#print(paste("acurrent", a[MCtime],", aproposed rejected=", a2,", alpha=", alpha,", u=",u ))
	 }# end else
	 } #end else
	
lnew=NA	 
} # for MCitr 1:n-1

## c1-c8
for (MCitr in 1:(n-1)){
curpars=a[MCitr,]
mu2=curpars[6:13]	#get out current guesses for the parameter block we are interested in

b2=mvrnorm(1,mu2,Sigma=erv22*diag(8))
#b2=rnorm(8,mu2,erv22) 
if (b2[1]<0 || b2[2]<0 || b2[3]<0 || b2[4]<0 || b2[5]<0 || b2[6]<0 || b2[7]<0 || b2[8]<0 || b2[1]>1|| b2[2]>1|| b2[3]>1|| b2[4]>1|| b2[5]>1|| b2[6]>1|| b2[7]>1|| b2[8]>1){
	curpars[6:13]=mu2
  a[(MCitr+1),]=a[MCitr,]
# print(paste("acurrent", a[MCtime],", aproposed rejected=", a2,"outside of the prior"))
} else {

	# to compute log-likelihood based on guess a2:
curpars[6:13]=b2	
lnew=myloglk14(a1=curpars,t=t,tby=tby,psdata=psdata,erv1=erv1)

 
## to compute M-H
  alpha=min(1,exp(lnew-lold))
   u=runif(1)
#   print(paste("MCtime=", MCtime,", lold=",lold, ", lnew=",lnew, "likratio=",exp(lnew-lold) ))
   if (u<=alpha){
   	curpars[6:13]=b2
	a[(MCitr+1),]=curpars
	count[2]=count[2]+1
	lold=lnew #the proposal has become the current (old) stage 
#	print(paste("acurrent", a[MCtime],", aproposed accepted=", a2,", alpha=", alpha,", u=",u ))
      } # end if
       else{
		curpars[6:13]=mu2
		a[(MCitr+1),]=a[MCitr,]
#print(paste("acurrent", a[MCtime],", aproposed rejected=", a2,", alpha=", alpha,", u=",u ))
	 }# end else
	 } #end else
	
lnew=NA	 
}

## rho
for (MCitr in 1:(n-1)){
curpars=a[MCitr,]
mu3=curpars[14]	#get out current guess for the mth parameter we are interested in

c2=rnorm(1,mu3,sd=sqrt(erv23)) 
if (c2[1]<0 || c2[1]>1){
	curpars[14]=mu3
   a[(MCitr+1),]=a[MCitr,]
# print(paste("acurrent", a[MCtime],", aproposed rejected=", a2,"outside of the prior"))
} else {

	# to compute log-likelihood based on guess a2:
curpars[14]=c2	
lnew=myloglk14(a1=curpars,t=t,tby=tby,psdata=psdata,erv1=erv1)

 
## to compute M-H
  alpha=min(1,exp(lnew-lold))
   u=runif(1)
#   print(paste("MCtime=", MCtime,", lold=",lold, ", lnew=",lnew, "likratio=",exp(lnew-lold) ))
   if (u<=alpha){
   	curpars[14]=c2
	a[(MCitr+1),]=curpars
	count[3]=count[3]+1
	lold=lnew #the proposal has become the current (old) stage 
#	print(paste("acurrent", a[MCtime],", aproposed accepted=", a2,", alpha=", alpha,", u=",u ))
      } # end if
       else{
		curpars[14]=mu3
		a[(MCitr+1),]=a[MCitr,]
#print(paste("acurrent", a[MCtime],", aproposed rejected=", a2,", alpha=", alpha,", u=",u ))
	 }# end else
	 } #end else
	
lnew=NA	 
}
print(paste('acceptance rate=',count/n,'l=',lold))	
return(a)}