#source("/Users/yilinsmac/Desktop/sigfile functions/14d/myMCMC14a_evk function.r")
## function to perform MCMC based on previous functions: 
myMCMC14a_evk=function(psdata,k=10,erv1=1,erv2=rep(0.01,14),t=50,tby=1,n=3000){ #psdata is the real data to deal with; erv1 is the noise variance, erv2 is the variance of proposal distribution; n is the number of times of MCMC.

# this loops over each parameter in one iteration.

# erv2 is a vector of normal proposal variance of dim 1*14

# k is such that we only record every kth iteration.

##  now start implementing MCMC:
 # "real"data is generated by previous function
erv2[14]=0
a={}
a0=rep(0.5,14)
a0[14]=0.01
#a0=runif(13) #so rho is also guessed from a uniform?
a=rbind(a,a0)
 
# log-likelihood l for datat using guess:
lold=myloglk14(a1=a0,t=t,tby=tby,psdata=psdata,erv1=erv1)
 

count=rep(0,14)
curpars=a0 #current 14-d parameter guess at iteration 0
# for loop to loop over n iterations
for (MCitr in 1:(n-1)){


# for loop to loop over 14 parameters
 for (m in 1:13){
mu=curpars[m]	#get out current guess for the mth parameter we are interested in

a2=rnorm(1,mu,erv2[m]) 
if (a2<0 || a2>1){
	curpars[m]=mu
 # a[(MCitr+1),]=a[MCitr,]
# print(paste("acurrent", a[MCtime],", aproposed rejected=", a2,"outside of the prior"))
} else {

	# to compute log-likelihood based on guess a2:
curpars[m]=a2	
lnew=myloglk14(a1=curpars,t=t,tby=tby,psdata=psdata,erv1=erv1)


 
## to compute M-H
  alpha=min(1,exp(lnew-lold))
   u=runif(1)
#   print(paste("MCtime=", MCtime,", lold=",lold, ", lnew=",lnew, "likratio=",exp(lnew-lold) ))
   if (u<=alpha){
   	curpars[m]=a2
	#a[(MCitr+1),]=curpars
	count[m]=count[m]+1
	lold=lnew #the proposal has become the current (old) stage 
#	print(paste("acurrent", a[MCtime],", aproposed accepted=", a2,", alpha=", alpha,", u=",u ))
      } # end if
       else{
		curpars[m]=mu
		#a[(MCitr+1),]=a[MCitr,]
#print(paste("acurrent", a[MCtime],", aproposed rejected=", a2,", alpha=", alpha,", u=",u ))
	 }# end else
	 } #end else
	lnew=NA	 
 }#end for m=1,...,13

lnew=NA	

## rho
mu3=curpars[14]	#get out current guess for the mth parameter we are interested in

c2=rnorm(1,mu3,sd=sqrt(erv2[14])) 
if (c2[1]<0 || c2[1]>1){
	curpars[14]=mu3
 # a[(MCitr+1),]=a[MCitr,]
# print(paste("acurrent", a[MCtime],", aproposed #rejected=", a2,"outside of the prior"))
} else {

	# to compute log-likelihood based on guess a2:
curpars[14]=c2	
lnew=myloglk14(a1=curpars,t=t,tby=tby,psdata=psdata,erv1=erv1)

 
## to compute M-H
  alpha=min(1,exp(lnew-lold)*mu3/c2)
   u=runif(1)
#   print(paste("MCtime=", MCtime,", lold=",lold, ", #lnew=",lnew, "likratio=",exp(lnew-lold) ))
   if (u<=alpha){
   	curpars[14]=c2
	#a[(MCitr+1),]=curpars
	count[14]=count[14]+1
	lold=lnew #the proposal has become the current (old) stage 
#	print(paste("acurrent", a[MCtime],", aproposed accepted=", a2,", alpha=", alpha,", u=",u ))
      } # end if
       else{
		curpars[14]=mu3
		#a[(MCitr+1),]=a[MCitr,]
#print(paste("acurrent", a[MCtime],", aproposed rejected=", a2,", alpha=", alpha,", u=",u ))
}# end else
	 } #end else
	
lnew=NA	 

if (MCitr %% k ==0){
a=rbind(a,curpars)
}

} #end for (MCtime 1:n-1)
print(paste('acceptance rate=',count/n,'lold=',lold,'a0=',a0))
return(a)
}