## function to perform MCMC based on previous functions: 
myMCMC=function(psdata,erv1=0.1,erv2=0.1,t=50,tby=1,n=3000,m,sf=0.1){ #psdata is the real data to deal with; erv1 is the noise variance, erv2 is the variance of proposal distribution; n is the number of times of MCMC.
# m is the index of the parameter to infer.

##  now start implementing MCMC:
 # "real"data is generated by previous function
a=rep(NA,n)
a0=runif(1) 
a[1]=a0
 
# log-likelihood l for datat using guess:
lold=myloglk(m=m,a1=a0,t=t,tby=tby,psdata=psdata,erv1=erv1,sf=sf)
count=0
# Using for-loop
for (MCtime in 1:(n-1)){
# now propose a new candidate for a:
a2=rnorm(1,a[MCtime],erv2) 
if (a2<0 || a2>1){
 a[MCtime+1]=a[MCtime]
# print(paste("acurrent", a[MCtime],", aproposed rejected=", a2,"outside of the prior"))
} else {

	# to compute log-likelihood based on guess a2:
	lnew=myloglk(m=m,a1=a2,t=t,tby=tby,psdata=psdata,erv1=erv1,sf=sf)

 
## to compute M-H
  alpha=min(1,exp(lnew-lold))
   u=runif(1)
#   print(paste("MCtime=", MCtime,", lold=",lold, ", lnew=",lnew, "likratio=",exp(lnew-lold) ))
   if (u<=alpha){
	a[MCtime+1]=a2
	lold=lnew
	count=count+1
#	print(paste("acurrent", a[MCtime],", aproposed accepted=", a2,", alpha=", alpha,", u=",u ))
      } # end if
       else{
		a[MCtime+1]=a[MCtime]
#print(paste("acurrent", a[MCtime],", aproposed rejected=", a2,", alpha=", alpha,", u=",u ))
	 }# end else
	 } #end else
	
lnew=NA	 
} #end for (MCtime 1:n-1)
print(paste("lold=",lold,'count=',count/n))
return(a)}