# trace plot
traceplot=function(a){ # a is the output of myMCMC, the sequence of candidate for parameter value generated by MCMC, plot the last 500.
	plot(tail(a,500),type='l',xlab="MCMC iteration", ylab="value for par", main="trace plot",ylim=c(0,1))
}
